CREATE TABLE PRICES (
         REFERENCE_ID VARCHAR(100),
         COUNTRY_CODE VARCHAR(100),
         CURRENCY_CODE VARCHAR(3),
         VALUE DOUBLE UNSIGNED,
         CREATED TIMESTAMP DEFAULT NOW()
);

ALTER TABLE PRICES ADD CONSTRAINT PK_PRICE_ID PRIMARY KEY (REFERENCE_ID, COUNTRY_CODE, CURRENCY_CODE);